"""Add budget column to projects

Revision ID: 2f8f1cc1807b
Revises: ae4b6f4d673a
Create Date: 2025-01-16 12:21:31.942455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f8f1cc1807b'
down_revision = 'ae4b6f4d673a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('budget', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'budget')
    # ### end Alembic commands ###
